### ISSUE TITLE
You said it: it's a bug :)

### ISSUE THREAD

**Issue by mircealungu** [JorritO/Zeeguu-Reader-iOS#1]
<img width="711" alt="screenshot 2016-02-03 12 20 11" src="https://cloud.githubusercontent.com/assets/464519/12790835/8e283b80-caa4-11e5-80a1-454bb0e54091.png">

**Comment by mircealungu** [comment]
When saving a word from the News Reader, the context captures also the previous translations. Not needed :)

**Comment by JorritO** [comment]
3cffe1e762ed92c894c4e604135dd3243c690be7 should fix this issue, I did a short test and it didn't happen anymore, could you do some test too?

**Comment by mircealungu** [comment]
Excellent. Let me try it and I'll let you know!

m.
