### ISSUE TITLE
crash - especially for you!

### ISSUE THREAD

**Issue by mircealungu** [JorritO/Zeeguu-Reader-iOS#3]
<img width="1788" alt="screenshot 2016-02-24 14 59 01" src="https://cloud.githubusercontent.com/assets/464519/13287407/372baa56-db07-11e5-8d56-08197b70e1b6.png">

**Comment by JorritO** [comment]
Fixed in commit 7d27eb78461f1c1a6cd9c2ddd5292a48c84de3de
